"""update schemas with uuid and relationships

Revision ID: cdb528f269b4
Revises: 521970224c1f
Create Date: 2026-06-08 12:48:20.576340

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import Vector

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdb528f269b4'
down_revision: Union[str, Sequence[str], None] = '521970224c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chunk_order', sa.Integer(), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('ix_chunk_asset_id', 'chunks', ['asset_id'], unique=False)
    op.create_index('ix_chunk_project_id', 'chunks', ['project_id'], unique=False)
    op.drop_table('datachunks')
    op.add_column('assets', sa.Column('uuid', sa.UUID(), nullable=False))
    op.add_column('assets', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('assets', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('assets', 'path',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.create_index('ix_asset_project_id', 'assets', ['project_id'], unique=False)
    op.create_index('ix_asset_type', 'assets', ['type'], unique=False)
    op.create_unique_constraint(None, 'assets', ['uuid'])
    op.add_column('projects', sa.Column('uuid', sa.UUID(), nullable=False))
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'projects', ['name'])
    op.create_unique_constraint(None, 'projects', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_column('projects', 'updated_at')
    op.drop_column('projects', 'uuid')
    op.drop_constraint(None, 'assets', type_='unique')
    op.drop_index('ix_asset_type', table_name='assets')
    op.drop_index('ix_asset_project_id', table_name='assets')
    op.alter_column('assets', 'path',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('assets', 'updated_at')
    op.drop_column('assets', 'config')
    op.drop_column('assets', 'uuid')
    op.create_table('datachunks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True),
    sa.Column('chunk_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('datachunks_asset_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('datachunks_pkey'))
    )
    op.drop_index('ix_chunk_project_id', table_name='chunks')
    op.drop_index('ix_chunk_asset_id', table_name='chunks')
    op.drop_table('chunks')
    # ### end Alembic commands ###
